#!/bin/bash

if [ -d "$1" ]; then
    echo directory
    CLICOLOR_FORCE=1 ls -G -l -h "$1"
    exit
fi

case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
    *.tar.gz|*.tgz|*.tar.bz2|*.tar.tb2|*.tbz|*.tbz2)
        echo tar
        du -h "$1" | cut -f1 | sed 's/ *//'
        tar -tf "$1"
        ;;

    *.gz)
        echo gzip
        gzcat "$1"
        ;;

    *.bz2)
        echo bzip2
        bzcat "$1"
        ;;

    *.zip)
        echo zip
        unzip -l "$1"
        ;;

esac

